// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[category]" | "/about" | "/accept-invite" | "/access" | "/advertise-with-us" | "/advertisement-enquiry" | "/analysis" | "/analysis/[slug]" | "/articles/[slug]" | "/auth/[[...auth]]" | "/auth/sso-callback" | "/author/[slug]" | "/authors" | "/case-study" | "/case-study/[slug]" | "/contact" | "/cookies" | "/cover-story" | "/cover-story/[slug]" | "/dashboard" | "/dashboard/bookmarks" | "/dashboard/content" | "/dashboard/events" | "/dashboard/feed" | "/dashboard/reports" | "/dashboard/settings" | "/dashboard/subscriptions" | "/data-retention" | "/download-media-kit" | "/editorial" | "/editorial/[slug]" | "/energclub" | "/energclub-info" | "/energclub/dashboard" | "/events" | "/events/[slug]" | "/feature" | "/feature/[slug]" | "/featured-stories" | "/featured-stories/[slug]" | "/interview" | "/interview/[slug]" | "/interviews" | "/interviews/[slug]" | "/issues" | "/issues/[slug]" | "/market/[symbol]" | "/membership-access" | "/membership-decline" | "/news" | "/news/[slug]" | "/onboarding" | "/opinion" | "/opinion/[slug]" | "/print/[slug]" | "/privacy" | "/register" | "/reports" | "/reports/[slug]" | "/search" | "/sectors" | "/sectors/[slug]" | "/subscribe" | "/tags/[slug]" | "/terms" | "/unsubscribe" | "/verify-access" | "/verify-account" | "/videos" | "/videos/[slug]"
type AppRouteHandlerRoutes = "/api/admin/retry-stuck-syncs" | "/api/admin/test-preference-digest" | "/api/auth/access-verify" | "/api/auth/confirm-otp" | "/api/auth/email-otp-send" | "/api/auth/email-verify" | "/api/auth/generate-invite" | "/api/auth/invite" | "/api/auth/magic-email-otp-send" | "/api/auth/magic-link" | "/api/auth/magic-otp-send" | "/api/auth/magic-otp-verify" | "/api/auth/membership-access" | "/api/auth/membership-qr" | "/api/auth/phone-verify" | "/api/auth/send-otp" | "/api/auth/signup" | "/api/auth/verify-account" | "/api/auth/verify-otp" | "/api/auth/verify-second" | "/api/brevo/sync-contact" | "/api/clerk/webhook" | "/api/community/posts" | "/api/community/posts/[id]" | "/api/community/posts/[id]/comments" | "/api/content" | "/api/crm/create-duplicate-lead" | "/api/crm/create-lead" | "/api/cron/abandoned-cart" | "/api/cron/preference-digests" | "/api/cron/weekly-reminders" | "/api/dashboard/events" | "/api/dashboard/feed" | "/api/leads/sync-brevo-to-zoho" | "/api/leads/zoho-webhook" | "/api/master/communities" | "/api/master/industries" | "/api/master/sub-industries" | "/api/membership/decline" | "/api/membership/generate-id" | "/api/menu" | "/api/onboarding/submit" | "/api/otp/send" | "/api/otp/verify" | "/api/profile/check" | "/api/revalidate" | "/api/search" | "/api/subscribe" | "/api/test-db" | "/api/unsubscribe" | "/api/user/profile" | "/api/user/update-profile" | "/api/webhooks/clerk" | "/api/zoho/callback" | "/api/zoho/create-contact" | "/api/zoho/create-lead" | "/api/zoho/form-lead" | "/api/zoho/provision" | "/api/zoho/update-lead-membership" | "/rss.xml" | "/rss/articles.xml" | "/rss/news.xml" | "/sitemap-articles.xml" | "/sitemap-news.xml" | "/sitemap-static.xml" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/advertise-with-us" | "/advertisement-enquiry" | "/auth" | "/contact" | "/dashboard" | "/download-media-kit" | "/editorial" | "/energclub" | "/energclub/dashboard" | "/events" | "/issues" | "/news" | "/opinion" | "/reports" | "/sectors" | "/sectors/[slug]" | "/subscribe" | "/videos"
type RedirectRoutes = "/advertise" | "/author" | "/interview" | "/interview/[slug]" | "/login" | "/news/delhi-announces-new-ev-policy-to-curb-pollution-expand-charging-network-1" | "/news/govt-steps-up-ev-charging-rollout-with-tighter-battery-standards-r-and-d-push-1"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[category]": { "category": string; }
  "/about": {}
  "/accept-invite": {}
  "/access": {}
  "/advertise": {}
  "/advertise-with-us": {}
  "/advertisement-enquiry": {}
  "/analysis": {}
  "/analysis/[slug]": { "slug": string; }
  "/api/admin/retry-stuck-syncs": {}
  "/api/admin/test-preference-digest": {}
  "/api/auth/access-verify": {}
  "/api/auth/confirm-otp": {}
  "/api/auth/email-otp-send": {}
  "/api/auth/email-verify": {}
  "/api/auth/generate-invite": {}
  "/api/auth/invite": {}
  "/api/auth/magic-email-otp-send": {}
  "/api/auth/magic-link": {}
  "/api/auth/magic-otp-send": {}
  "/api/auth/magic-otp-verify": {}
  "/api/auth/membership-access": {}
  "/api/auth/membership-qr": {}
  "/api/auth/phone-verify": {}
  "/api/auth/send-otp": {}
  "/api/auth/signup": {}
  "/api/auth/verify-account": {}
  "/api/auth/verify-otp": {}
  "/api/auth/verify-second": {}
  "/api/brevo/sync-contact": {}
  "/api/clerk/webhook": {}
  "/api/community/posts": {}
  "/api/community/posts/[id]": { "id": string; }
  "/api/community/posts/[id]/comments": { "id": string; }
  "/api/content": {}
  "/api/crm/create-duplicate-lead": {}
  "/api/crm/create-lead": {}
  "/api/cron/abandoned-cart": {}
  "/api/cron/preference-digests": {}
  "/api/cron/weekly-reminders": {}
  "/api/dashboard/events": {}
  "/api/dashboard/feed": {}
  "/api/leads/sync-brevo-to-zoho": {}
  "/api/leads/zoho-webhook": {}
  "/api/master/communities": {}
  "/api/master/industries": {}
  "/api/master/sub-industries": {}
  "/api/membership/decline": {}
  "/api/membership/generate-id": {}
  "/api/menu": {}
  "/api/onboarding/submit": {}
  "/api/otp/send": {}
  "/api/otp/verify": {}
  "/api/profile/check": {}
  "/api/revalidate": {}
  "/api/search": {}
  "/api/subscribe": {}
  "/api/test-db": {}
  "/api/unsubscribe": {}
  "/api/user/profile": {}
  "/api/user/update-profile": {}
  "/api/webhooks/clerk": {}
  "/api/zoho/callback": {}
  "/api/zoho/create-contact": {}
  "/api/zoho/create-lead": {}
  "/api/zoho/form-lead": {}
  "/api/zoho/provision": {}
  "/api/zoho/update-lead-membership": {}
  "/articles/[slug]": { "slug": string; }
  "/auth": {}
  "/auth/[[...auth]]": { "auth"?: string[]; }
  "/auth/sso-callback": {}
  "/author": {}
  "/author/[slug]": { "slug": string; }
  "/authors": {}
  "/case-study": {}
  "/case-study/[slug]": { "slug": string; }
  "/contact": {}
  "/cookies": {}
  "/cover-story": {}
  "/cover-story/[slug]": { "slug": string; }
  "/dashboard": {}
  "/dashboard/bookmarks": {}
  "/dashboard/content": {}
  "/dashboard/events": {}
  "/dashboard/feed": {}
  "/dashboard/reports": {}
  "/dashboard/settings": {}
  "/dashboard/subscriptions": {}
  "/data-retention": {}
  "/download-media-kit": {}
  "/editorial": {}
  "/editorial/[slug]": { "slug": string; }
  "/energclub": {}
  "/energclub-info": {}
  "/energclub/dashboard": {}
  "/events": {}
  "/events/[slug]": { "slug": string; }
  "/feature": {}
  "/feature/[slug]": { "slug": string; }
  "/featured-stories": {}
  "/featured-stories/[slug]": { "slug": string; }
  "/interview": {}
  "/interview/[slug]": { "slug": string; }
  "/interviews": {}
  "/interviews/[slug]": { "slug": string; }
  "/issues": {}
  "/issues/[slug]": { "slug": string; }
  "/login": {}
  "/market/[symbol]": { "symbol": string; }
  "/membership-access": {}
  "/membership-decline": {}
  "/news": {}
  "/news/[slug]": { "slug": string; }
  "/news/delhi-announces-new-ev-policy-to-curb-pollution-expand-charging-network-1": {}
  "/news/govt-steps-up-ev-charging-rollout-with-tighter-battery-standards-r-and-d-push-1": {}
  "/onboarding": {}
  "/opinion": {}
  "/opinion/[slug]": { "slug": string; }
  "/print/[slug]": { "slug": string; }
  "/privacy": {}
  "/register": {}
  "/reports": {}
  "/reports/[slug]": { "slug": string; }
  "/rss.xml": {}
  "/rss/articles.xml": {}
  "/rss/news.xml": {}
  "/search": {}
  "/sectors": {}
  "/sectors/[slug]": { "slug": string; }
  "/sitemap-articles.xml": {}
  "/sitemap-news.xml": {}
  "/sitemap-static.xml": {}
  "/sitemap.xml": {}
  "/subscribe": {}
  "/tags/[slug]": { "slug": string; }
  "/terms": {}
  "/unsubscribe": {}
  "/verify-access": {}
  "/verify-account": {}
  "/videos": {}
  "/videos/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/advertise-with-us": never
  "/advertisement-enquiry": never
  "/auth": never
  "/contact": never
  "/dashboard": never
  "/download-media-kit": never
  "/editorial": never
  "/energclub": never
  "/energclub/dashboard": never
  "/events": never
  "/issues": never
  "/news": never
  "/opinion": never
  "/reports": never
  "/sectors": never
  "/sectors/[slug]": never
  "/subscribe": never
  "/videos": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
