// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(routes)/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[category]">> = Specific
  const handler = {} as typeof import("../../app/(routes)/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/accept-invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accept-invite">> = Specific
  const handler = {} as typeof import("../../app/accept-invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access">> = Specific
  const handler = {} as typeof import("../../app/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advertise-with-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advertise-with-us">> = Specific
  const handler = {} as typeof import("../../app/advertise-with-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advertisement-enquiry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advertisement-enquiry">> = Specific
  const handler = {} as typeof import("../../app/advertisement-enquiry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analysis/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analysis/[slug]">> = Specific
  const handler = {} as typeof import("../../app/analysis/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analysis">> = Specific
  const handler = {} as typeof import("../../app/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/articles/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles/[slug]">> = Specific
  const handler = {} as typeof import("../../app/articles/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/[[...auth]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/[[...auth]]">> = Specific
  const handler = {} as typeof import("../../app/auth/[[...auth]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/sso-callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sso-callback">> = Specific
  const handler = {} as typeof import("../../app/auth/sso-callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/author/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/author/[slug]">> = Specific
  const handler = {} as typeof import("../../app/author/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/authors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authors">> = Specific
  const handler = {} as typeof import("../../app/authors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-study/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-study/[slug]">> = Specific
  const handler = {} as typeof import("../../app/case-study/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-study/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-study">> = Specific
  const handler = {} as typeof import("../../app/case-study/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cover-story/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cover-story/[slug]">> = Specific
  const handler = {} as typeof import("../../app/cover-story/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cover-story/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cover-story">> = Specific
  const handler = {} as typeof import("../../app/cover-story/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookmarks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/content">> = Specific
  const handler = {} as typeof import("../../app/dashboard/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/feed">> = Specific
  const handler = {} as typeof import("../../app/dashboard/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/subscriptions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-retention/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-retention">> = Specific
  const handler = {} as typeof import("../../app/data-retention/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/download-media-kit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/download-media-kit">> = Specific
  const handler = {} as typeof import("../../app/download-media-kit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editorial/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editorial/[slug]">> = Specific
  const handler = {} as typeof import("../../app/editorial/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editorial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editorial">> = Specific
  const handler = {} as typeof import("../../app/editorial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/energclub-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/energclub-info">> = Specific
  const handler = {} as typeof import("../../app/energclub-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/energclub/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/energclub/dashboard">> = Specific
  const handler = {} as typeof import("../../app/energclub/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/energclub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/energclub">> = Specific
  const handler = {} as typeof import("../../app/energclub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]">> = Specific
  const handler = {} as typeof import("../../app/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feature/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feature/[slug]">> = Specific
  const handler = {} as typeof import("../../app/feature/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feature/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feature">> = Specific
  const handler = {} as typeof import("../../app/feature/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/featured-stories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/featured-stories/[slug]">> = Specific
  const handler = {} as typeof import("../../app/featured-stories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/featured-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/featured-stories">> = Specific
  const handler = {} as typeof import("../../app/featured-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/interview/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]">> = Specific
  const handler = {} as typeof import("../../app/interview/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview">> = Specific
  const handler = {} as typeof import("../../app/interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/interviews/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interviews/[slug]">> = Specific
  const handler = {} as typeof import("../../app/interviews/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interviews">> = Specific
  const handler = {} as typeof import("../../app/interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/issues/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/issues/[slug]">> = Specific
  const handler = {} as typeof import("../../app/issues/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/issues">> = Specific
  const handler = {} as typeof import("../../app/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/[symbol]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market/[symbol]">> = Specific
  const handler = {} as typeof import("../../app/market/[symbol]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/membership-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/membership-access">> = Specific
  const handler = {} as typeof import("../../app/membership-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/membership-decline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/membership-decline">> = Specific
  const handler = {} as typeof import("../../app/membership-decline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[slug]">> = Specific
  const handler = {} as typeof import("../../app/news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/opinion/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opinion/[slug]">> = Specific
  const handler = {} as typeof import("../../app/opinion/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/opinion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opinion">> = Specific
  const handler = {} as typeof import("../../app/opinion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/print/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print/[slug]">> = Specific
  const handler = {} as typeof import("../../app/print/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/[slug]">> = Specific
  const handler = {} as typeof import("../../app/reports/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors/[slug]">> = Specific
  const handler = {} as typeof import("../../app/sectors/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors">> = Specific
  const handler = {} as typeof import("../../app/sectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe">> = Specific
  const handler = {} as typeof import("../../app/subscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tags/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags/[slug]">> = Specific
  const handler = {} as typeof import("../../app/tags/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-access">> = Specific
  const handler = {} as typeof import("../../app/verify-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-account">> = Specific
  const handler = {} as typeof import("../../app/verify-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/videos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos/[slug]">> = Specific
  const handler = {} as typeof import("../../app/videos/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos">> = Specific
  const handler = {} as typeof import("../../app/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/retry-stuck-syncs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/retry-stuck-syncs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/retry-stuck-syncs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/test-preference-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-preference-digest">> = Specific
  const handler = {} as typeof import("../../app/api/admin/test-preference-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/access-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/access-verify">> = Specific
  const handler = {} as typeof import("../../app/api/auth/access-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/confirm-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/confirm-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/confirm-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/email-otp-send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/email-otp-send">> = Specific
  const handler = {} as typeof import("../../app/api/auth/email-otp-send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/email-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/email-verify">> = Specific
  const handler = {} as typeof import("../../app/api/auth/email-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/generate-invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/generate-invite">> = Specific
  const handler = {} as typeof import("../../app/api/auth/generate-invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/invite">> = Specific
  const handler = {} as typeof import("../../app/api/auth/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/magic-email-otp-send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-email-otp-send">> = Specific
  const handler = {} as typeof import("../../app/api/auth/magic-email-otp-send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link">> = Specific
  const handler = {} as typeof import("../../app/api/auth/magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/magic-otp-send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-otp-send">> = Specific
  const handler = {} as typeof import("../../app/api/auth/magic-otp-send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/magic-otp-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-otp-verify">> = Specific
  const handler = {} as typeof import("../../app/api/auth/magic-otp-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/membership-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/membership-access">> = Specific
  const handler = {} as typeof import("../../app/api/auth/membership-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/membership-qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/membership-qr">> = Specific
  const handler = {} as typeof import("../../app/api/auth/membership-qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/phone-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/phone-verify">> = Specific
  const handler = {} as typeof import("../../app/api/auth/phone-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-account/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-account">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-second/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-second">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-second/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/brevo/sync-contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brevo/sync-contact">> = Specific
  const handler = {} as typeof import("../../app/api/brevo/sync-contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clerk/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clerk/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/clerk/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/community/posts/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/community/posts/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/community/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/community/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/community/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts">> = Specific
  const handler = {} as typeof import("../../app/api/community/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content">> = Specific
  const handler = {} as typeof import("../../app/api/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crm/create-duplicate-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/create-duplicate-lead">> = Specific
  const handler = {} as typeof import("../../app/api/crm/create-duplicate-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crm/create-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/create-lead">> = Specific
  const handler = {} as typeof import("../../app/api/crm/create-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/abandoned-cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/abandoned-cart">> = Specific
  const handler = {} as typeof import("../../app/api/cron/abandoned-cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/preference-digests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/preference-digests">> = Specific
  const handler = {} as typeof import("../../app/api/cron/preference-digests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/weekly-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/weekly-reminders">> = Specific
  const handler = {} as typeof import("../../app/api/cron/weekly-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/events">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/feed">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/sync-brevo-to-zoho/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/sync-brevo-to-zoho">> = Specific
  const handler = {} as typeof import("../../app/api/leads/sync-brevo-to-zoho/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/zoho-webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/zoho-webhook">> = Specific
  const handler = {} as typeof import("../../app/api/leads/zoho-webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/master/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master/communities">> = Specific
  const handler = {} as typeof import("../../app/api/master/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/master/industries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master/industries">> = Specific
  const handler = {} as typeof import("../../app/api/master/industries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/master/sub-industries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master/sub-industries">> = Specific
  const handler = {} as typeof import("../../app/api/master/sub-industries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/membership/decline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/membership/decline">> = Specific
  const handler = {} as typeof import("../../app/api/membership/decline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/membership/generate-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/membership/generate-id">> = Specific
  const handler = {} as typeof import("../../app/api/membership/generate-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu">> = Specific
  const handler = {} as typeof import("../../app/api/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/submit">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/otp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/otp/send">> = Specific
  const handler = {} as typeof import("../../app/api/otp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/otp/verify">> = Specific
  const handler = {} as typeof import("../../app/api/otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/check">> = Specific
  const handler = {} as typeof import("../../app/api/profile/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-db">> = Specific
  const handler = {} as typeof import("../../app/api/test-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/api/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/update-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/update-profile">> = Specific
  const handler = {} as typeof import("../../app/api/user/update-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/clerk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/clerk">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/clerk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/callback">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/create-contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/create-contact">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/create-contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/create-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/create-lead">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/create-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/form-lead/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/form-lead">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/form-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/provision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/provision">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/provision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zoho/update-lead-membership/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zoho/update-lead-membership">> = Specific
  const handler = {} as typeof import("../../app/api/zoho/update-lead-membership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rss.xml">> = Specific
  const handler = {} as typeof import("../../app/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rss/articles.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rss/articles.xml">> = Specific
  const handler = {} as typeof import("../../app/rss/articles.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rss/news.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rss/news.xml">> = Specific
  const handler = {} as typeof import("../../app/rss/news.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-articles.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-articles.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap-articles.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-news.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-news.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap-news.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-static.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-static.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap-static.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advertise-with-us/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/advertise-with-us">> = Specific
  const handler = {} as typeof import("../../app/advertise-with-us/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advertisement-enquiry/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/advertisement-enquiry">> = Specific
  const handler = {} as typeof import("../../app/advertisement-enquiry/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/download-media-kit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/download-media-kit">> = Specific
  const handler = {} as typeof import("../../app/download-media-kit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editorial/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/editorial">> = Specific
  const handler = {} as typeof import("../../app/editorial/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/energclub/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/energclub/dashboard">> = Specific
  const handler = {} as typeof import("../../app/energclub/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/energclub/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/energclub">> = Specific
  const handler = {} as typeof import("../../app/energclub/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/issues/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/issues">> = Specific
  const handler = {} as typeof import("../../app/issues/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/news">> = Specific
  const handler = {} as typeof import("../../app/news/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/opinion/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/opinion">> = Specific
  const handler = {} as typeof import("../../app/opinion/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/reports/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sectors/[slug]">> = Specific
  const handler = {} as typeof import("../../app/sectors/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sectors">> = Specific
  const handler = {} as typeof import("../../app/sectors/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscribe/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/subscribe">> = Specific
  const handler = {} as typeof import("../../app/subscribe/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/videos/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/videos">> = Specific
  const handler = {} as typeof import("../../app/videos/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
