import type {
  EnergyEvent,
  EventResource,
  Region,
  ResourceType,
  Sector,
  SortOption,
} from "./types";

export const EVENT_OPTIONS = [
  "ADIPEC",
  "India Energy Week",
  "Gastech",
  "Offshore Europe",
  "Future Energy Asia",
  "Custom Event List",
] as const;

export const RESOURCE_TYPE_OPTIONS: ResourceType[] = [
  "Event Brochure",
  "Post Show Report",
  "Whitepaper",
  "Industry Report",
  "Presentation",
  "Media Kit",
  "Sponsor Prospectus",
];

export const SECTOR_OPTIONS: Sector[] = [
  "Oil & Gas",
  "Power Generation",
  "Renewables",
  "Transmission",
  "Distribution",
  "Electricity Markets",
  "New Energies",
  "Energy Storage",
  "Sustainability & Safety",
];

export const YEAR_OPTIONS = [2026, 2025, 2024, 2023] as const;

export const REGION_OPTIONS: Region[] = [
  "Middle East",
  "Asia",
  "Europe",
  "Africa",
  "North America",
];

export const SORT_OPTIONS: SortOption[] = [
  "Latest First",
  "Most Downloaded",
  "Popular",
  "Event Name",
];

export const EVENTS: EnergyEvent[] = [
  {
    id: "adipec",
    name: "ADIPEC",
    logoLabel: "AD",
    location: "Abu Dhabi, UAE",
    region: "Middle East",
    brandColor: "#0F766E",
    totalResources: 4,
  },
  {
    id: "india-energy-week",
    name: "India Energy Week",
    logoLabel: "IEW",
    location: "Goa, India",
    region: "Asia",
    brandColor: "#166534",
    totalResources: 4,
  },
  {
    id: "gastech",
    name: "Gastech",
    logoLabel: "GT",
    location: "Milan, Italy",
    region: "Europe",
    brandColor: "#1D4ED8",
    totalResources: 4,
  },
  {
    id: "offshore-europe",
    name: "Offshore Europe",
    logoLabel: "OE",
    location: "Aberdeen, UK",
    region: "Europe",
    brandColor: "#334155",
    totalResources: 3,
  },
  {
    id: "future-energy-asia",
    name: "Future Energy Asia",
    logoLabel: "FEA",
    location: "Bangkok, Thailand",
    region: "Asia",
    brandColor: "#B45309",
    totalResources: 4,
  },
  {
    id: "custom-event-list",
    name: "Custom Event List",
    logoLabel: "CE",
    location: "User-defined pipeline",
    region: "North America",
    brandColor: "#52525B",
    totalResources: 0,
  },
];

export const RESOURCES: EventResource[] = [
  {
    id: "adipec-2026-delegate-brochure",
    event_id: "adipec",
    resource_type: "Event Brochure",
    file_url: "/mock-downloads/adipec-2026-delegate-brochure.pdf",
    fileName: "adipec-2026-delegate-brochure.pdf",
    thumbnail: "Middle East energy strategy",
    title: "ADIPEC 2026 Strategic Delegate Brochure",
    eventName: "ADIPEC",
    eventLogo: "AD",
    year: 2026,
    sector: ["Oil & Gas", "New Energies", "Sustainability & Safety"],
    region: "Middle East",
    description:
      "A high-level event prospectus covering strategic themes, delegate pathways, show-floor programs, and executive networking opportunities.",
    fileType: "PDF",
    fileSize: "8.4 MB",
    pages: 36,
    downloads: 18400,
    popularity: 97,
    publishedAt: "2026-05-18",
    readTime: "14 min",
  },
  {
    id: "adipec-2025-post-show",
    event_id: "adipec",
    resource_type: "Post Show Report",
    file_url: "/mock-downloads/adipec-2025-post-show-report.pdf",
    fileName: "adipec-2025-post-show-report.pdf",
    thumbnail: "Executive attendance report",
    title: "ADIPEC 2025 Post Show Market Report",
    eventName: "ADIPEC",
    eventLogo: "AD",
    year: 2025,
    sector: ["Oil & Gas", "Power Generation"],
    region: "Middle East",
    description:
      "Attendance performance, buyer intent signals, conference highlights, and sector-level demand indicators from ADIPEC 2025.",
    fileType: "PDF",
    fileSize: "12.1 MB",
    pages: 48,
    downloads: 22310,
    popularity: 99,
    publishedAt: "2025-12-08",
    readTime: "18 min",
  },
  {
    id: "adipec-2026-sponsor-prospectus",
    event_id: "adipec",
    resource_type: "Sponsor Prospectus",
    file_url: "/mock-downloads/adipec-2026-sponsor-prospectus.pdf",
    fileName: "adipec-2026-sponsor-prospectus.pdf",
    thumbnail: "Sponsorship inventory",
    title: "ADIPEC 2026 Sponsor Prospectus",
    eventName: "ADIPEC",
    eventLogo: "AD",
    year: 2026,
    sector: ["Oil & Gas", "New Energies"],
    region: "Middle East",
    description:
      "Premium sponsorship packages, executive visibility options, hosted buyer formats, and brand activation opportunities.",
    fileType: "PDF",
    fileSize: "6.8 MB",
    pages: 28,
    downloads: 9700,
    popularity: 88,
    publishedAt: "2026-04-04",
    readTime: "11 min",
  },
  {
    id: "adipec-hydrogen-investment-outlook",
    event_id: "adipec",
    resource_type: "Whitepaper",
    file_url: "/mock-downloads/adipec-hydrogen-investment-outlook.pdf",
    fileName: "adipec-hydrogen-investment-outlook.pdf",
    thumbnail: "Hydrogen investment outlook",
    title: "Hydrogen Corridors and Capital Allocation Outlook",
    eventName: "ADIPEC",
    eventLogo: "AD",
    year: 2025,
    sector: ["New Energies", "Sustainability & Safety"],
    region: "Middle East",
    description:
      "A whitepaper on hydrogen corridor development, offtake constraints, policy mechanisms, and bankability signals across emerging markets.",
    fileType: "PDF",
    fileSize: "9.6 MB",
    pages: 42,
    downloads: 11280,
    popularity: 91,
    publishedAt: "2025-09-22",
    readTime: "16 min",
  },
  {
    id: "iew-2026-brochure",
    event_id: "india-energy-week",
    resource_type: "Event Brochure",
    file_url: "/mock-downloads/india-energy-week-2026-brochure.pdf",
    fileName: "india-energy-week-2026-brochure.pdf",
    thumbnail: "India energy transition",
    title: "India Energy Week 2026 Event Brochure",
    eventName: "India Energy Week",
    eventLogo: "IEW",
    year: 2026,
    sector: ["Oil & Gas", "Renewables", "Power Generation"],
    region: "Asia",
    description:
      "Program themes, exhibition zones, ministerial forums, and strategic participation options for India's flagship energy gathering.",
    fileType: "PDF",
    fileSize: "7.2 MB",
    pages: 34,
    downloads: 16220,
    popularity: 95,
    publishedAt: "2026-05-02",
    readTime: "13 min",
  },
  {
    id: "iew-2025-post-show",
    event_id: "india-energy-week",
    resource_type: "Post Show Report",
    file_url: "/mock-downloads/india-energy-week-2025-post-show-report.pdf",
    fileName: "india-energy-week-2025-post-show-report.pdf",
    thumbnail: "India post show insights",
    title: "India Energy Week 2025 Post Show Report",
    eventName: "India Energy Week",
    eventLogo: "IEW",
    year: 2025,
    sector: ["Power Generation", "Renewables", "New Energies"],
    region: "Asia",
    description:
      "Visitor analytics, conference insights, international participation, and opportunity mapping across India's energy value chain.",
    fileType: "PDF",
    fileSize: "10.5 MB",
    pages: 52,
    downloads: 19830,
    popularity: 98,
    publishedAt: "2025-02-26",
    readTime: "19 min",
  },
  {
    id: "iew-2026-transition-presentation",
    event_id: "india-energy-week",
    resource_type: "Presentation",
    file_url: "/mock-downloads/india-energy-week-2026-transition-presentation.ppt",
    fileName: "india-energy-week-2026-transition-presentation.ppt",
    thumbnail: "Transition boardroom deck",
    title: "India Transition Finance Presentation Deck",
    eventName: "India Energy Week",
    eventLogo: "IEW",
    year: 2026,
    sector: ["Renewables", "Energy Storage", "Sustainability & Safety"],
    region: "Asia",
    description:
      "An executive deck covering transition finance, grid modernization, storage economics, and investor-ready project themes.",
    fileType: "PPT",
    fileSize: "18.9 MB",
    pages: 44,
    downloads: 8350,
    popularity: 86,
    publishedAt: "2026-03-12",
    readTime: "12 min",
  },
  {
    id: "iew-2026-media-kit",
    event_id: "india-energy-week",
    resource_type: "Media Kit",
    file_url: "/mock-downloads/india-energy-week-2026-media-kit.zip",
    fileName: "india-energy-week-2026-media-kit.zip",
    thumbnail: "Media kit assets",
    title: "India Energy Week 2026 Media Kit",
    eventName: "India Energy Week",
    eventLogo: "IEW",
    year: 2026,
    sector: ["Oil & Gas", "Renewables"],
    region: "Asia",
    description:
      "Approved logos, campaign visuals, editorial boilerplates, social templates, and partner-ready media assets.",
    fileType: "ZIP",
    fileSize: "64.0 MB",
    pages: 18,
    downloads: 6490,
    popularity: 79,
    publishedAt: "2026-02-15",
    readTime: "7 min",
  },
  {
    id: "gastech-2026-brochure",
    event_id: "gastech",
    resource_type: "Event Brochure",
    file_url: "/mock-downloads/gastech-2026-brochure.pdf",
    fileName: "gastech-2026-brochure.pdf",
    thumbnail: "Gas LNG conference",
    title: "Gastech 2026 Global Gas & LNG Brochure",
    eventName: "Gastech",
    eventLogo: "GT",
    year: 2026,
    sector: ["Oil & Gas", "New Energies"],
    region: "Europe",
    description:
      "A delegate and exhibitor guide for LNG, gas, hydrogen, climate technology, and downstream energy leaders.",
    fileType: "PDF",
    fileSize: "7.9 MB",
    pages: 32,
    downloads: 14120,
    popularity: 92,
    publishedAt: "2026-04-26",
    readTime: "12 min",
  },
  {
    id: "gastech-2025-lng-report",
    event_id: "gastech",
    resource_type: "Industry Report",
    file_url: "/mock-downloads/gastech-2025-lng-demand-report.pdf",
    fileName: "gastech-2025-lng-demand-report.pdf",
    thumbnail: "LNG demand scenarios",
    title: "Global LNG Demand Scenarios Report",
    eventName: "Gastech",
    eventLogo: "GT",
    year: 2025,
    sector: ["Oil & Gas", "Power Generation"],
    region: "Europe",
    description:
      "Scenario analysis for LNG demand growth, flexible contracting, infrastructure bottlenecks, and Asia-Europe trade flows.",
    fileType: "PDF",
    fileSize: "11.4 MB",
    pages: 58,
    downloads: 17560,
    popularity: 96,
    publishedAt: "2025-10-14",
    readTime: "21 min",
  },
  {
    id: "gastech-2025-post-show",
    event_id: "gastech",
    resource_type: "Post Show Report",
    file_url: "/mock-downloads/gastech-2025-post-show-report.pdf",
    fileName: "gastech-2025-post-show-report.pdf",
    thumbnail: "Gastech post show",
    title: "Gastech 2025 Post Show Report",
    eventName: "Gastech",
    eventLogo: "GT",
    year: 2025,
    sector: ["Oil & Gas", "New Energies", "Sustainability & Safety"],
    region: "Europe",
    description:
      "Commercial outcomes, delegate mix, conference themes, and procurement intent benchmarks from the global gas community.",
    fileType: "PDF",
    fileSize: "10.2 MB",
    pages: 46,
    downloads: 15640,
    popularity: 90,
    publishedAt: "2025-11-02",
    readTime: "17 min",
  },
  {
    id: "gastech-2026-sponsor-prospectus",
    event_id: "gastech",
    resource_type: "Sponsor Prospectus",
    file_url: "/mock-downloads/gastech-2026-sponsor-prospectus.pdf",
    fileName: "gastech-2026-sponsor-prospectus.pdf",
    thumbnail: "Gastech sponsor plan",
    title: "Gastech 2026 Sponsor Prospectus",
    eventName: "Gastech",
    eventLogo: "GT",
    year: 2026,
    sector: ["Oil & Gas", "New Energies"],
    region: "Europe",
    description:
      "Sponsorship packages for senior commercial audiences across LNG, hydrogen, climate technology, and energy security.",
    fileType: "PDF",
    fileSize: "6.1 MB",
    pages: 26,
    downloads: 7820,
    popularity: 82,
    publishedAt: "2026-01-28",
    readTime: "10 min",
  },
  {
    id: "offshore-europe-2025-post-show",
    event_id: "offshore-europe",
    resource_type: "Post Show Report",
    file_url: "/mock-downloads/offshore-europe-2025-post-show-report.pdf",
    fileName: "offshore-europe-2025-post-show-report.pdf",
    thumbnail: "Offshore Europe outcomes",
    title: "Offshore Europe 2025 Post Show Report",
    eventName: "Offshore Europe",
    eventLogo: "OE",
    year: 2025,
    sector: ["Oil & Gas", "Sustainability & Safety"],
    region: "Europe",
    description:
      "Market sentiment, operator participation, technology demand, and supply chain investment themes from the offshore sector.",
    fileType: "PDF",
    fileSize: "9.9 MB",
    pages: 40,
    downloads: 10330,
    popularity: 85,
    publishedAt: "2025-09-18",
    readTime: "15 min",
  },
  {
    id: "offshore-europe-2024-transition-whitepaper",
    event_id: "offshore-europe",
    resource_type: "Whitepaper",
    file_url: "/mock-downloads/offshore-europe-transition-whitepaper.pdf",
    fileName: "offshore-europe-transition-whitepaper.pdf",
    thumbnail: "Offshore transition",
    title: "Offshore Decarbonization and Asset Integrity Whitepaper",
    eventName: "Offshore Europe",
    eventLogo: "OE",
    year: 2024,
    sector: ["Oil & Gas", "Sustainability & Safety", "Energy Storage"],
    region: "Europe",
    description:
      "A technical outlook on brownfield emissions reduction, offshore electrification, asset integrity, and adjacent storage models.",
    fileType: "PDF",
    fileSize: "8.7 MB",
    pages: 38,
    downloads: 8940,
    popularity: 83,
    publishedAt: "2024-09-06",
    readTime: "14 min",
  },
  {
    id: "offshore-europe-2025-presentation",
    event_id: "offshore-europe",
    resource_type: "Presentation",
    file_url: "/mock-downloads/offshore-europe-2025-boardroom-deck.ppt",
    fileName: "offshore-europe-2025-boardroom-deck.ppt",
    thumbnail: "Boardroom offshore deck",
    title: "North Sea Transition Boardroom Deck",
    eventName: "Offshore Europe",
    eventLogo: "OE",
    year: 2025,
    sector: ["Oil & Gas", "Renewables"],
    region: "Europe",
    description:
      "A concise executive deck on North Sea production outlook, offshore wind adjacency, emissions targets, and capex discipline.",
    fileType: "PPT",
    fileSize: "15.2 MB",
    pages: 32,
    downloads: 5120,
    popularity: 72,
    publishedAt: "2025-06-27",
    readTime: "9 min",
  },
  {
    id: "fea-2026-brochure",
    event_id: "future-energy-asia",
    resource_type: "Event Brochure",
    file_url: "/mock-downloads/future-energy-asia-2026-brochure.pdf",
    fileName: "future-energy-asia-2026-brochure.pdf",
    thumbnail: "Asia power investment",
    title: "Future Energy Asia 2026 Event Brochure",
    eventName: "Future Energy Asia",
    eventLogo: "FEA",
    year: 2026,
    sector: ["Power Generation", "Renewables", "New Energies"],
    region: "Asia",
    description:
      "A regional event guide for power, renewables, hydrogen, energy storage, grid investment, and transition finance communities.",
    fileType: "PDF",
    fileSize: "7.5 MB",
    pages: 34,
    downloads: 11910,
    popularity: 89,
    publishedAt: "2026-03-22",
    readTime: "12 min",
  },
  {
    id: "fea-2025-post-show",
    event_id: "future-energy-asia",
    resource_type: "Post Show Report",
    file_url: "/mock-downloads/future-energy-asia-2025-post-show-report.pdf",
    fileName: "future-energy-asia-2025-post-show-report.pdf",
    thumbnail: "Future Energy Asia report",
    title: "Future Energy Asia 2025 Post Show Report",
    eventName: "Future Energy Asia",
    eventLogo: "FEA",
    year: 2025,
    sector: ["Renewables", "Power Generation", "Energy Storage"],
    region: "Asia",
    description:
      "Commercial outcomes, country participation, project announcements, and technology themes across Southeast Asia's transition market.",
    fileType: "PDF",
    fileSize: "10.8 MB",
    pages: 50,
    downloads: 13270,
    popularity: 90,
    publishedAt: "2025-05-28",
    readTime: "18 min",
  },
  {
    id: "fea-storage-market-brief",
    event_id: "future-energy-asia",
    resource_type: "Industry Report",
    file_url: "/mock-downloads/future-energy-asia-storage-market-brief.pdf",
    fileName: "future-energy-asia-storage-market-brief.pdf",
    thumbnail: "Storage market brief",
    title: "Southeast Asia Storage Market Brief",
    eventName: "Future Energy Asia",
    eventLogo: "FEA",
    year: 2024,
    sector: ["Energy Storage", "Renewables", "Power Generation"],
    region: "Asia",
    description:
      "Project pipeline, revenue stack evolution, grid constraints, and procurement models for utility-scale storage in Southeast Asia.",
    fileType: "PDF",
    fileSize: "8.1 MB",
    pages: 35,
    downloads: 10110,
    popularity: 84,
    publishedAt: "2024-12-12",
    readTime: "13 min",
  },
  {
    id: "fea-2026-sponsor-prospectus",
    event_id: "future-energy-asia",
    resource_type: "Sponsor Prospectus",
    file_url: "/mock-downloads/future-energy-asia-2026-sponsor-prospectus.pdf",
    fileName: "future-energy-asia-2026-sponsor-prospectus.pdf",
    thumbnail: "Asia sponsor options",
    title: "Future Energy Asia 2026 Sponsor Prospectus",
    eventName: "Future Energy Asia",
    eventLogo: "FEA",
    year: 2026,
    sector: ["Power Generation", "New Energies", "Renewables"],
    region: "Asia",
    description:
      "Sponsorship architecture for utilities, technology providers, investors, and country pavilions targeting Asian growth markets.",
    fileType: "PDF",
    fileSize: "5.8 MB",
    pages: 24,
    downloads: 6180,
    popularity: 77,
    publishedAt: "2026-01-20",
    readTime: "8 min",
  },
];
