import { NextRequest, NextResponse } from "next/server";
import { clerkClient } from "@clerk/nextjs/server";
import { getLeadByEmail } from "@/lib/zoho";
import { verifyMagicToken } from "@/lib/magic-token";

export async function GET(request: NextRequest) {
    const searchParams = request.nextUrl.searchParams;
    const token = searchParams.get("token");
    const email = searchParams.get("email");

    if (!token || !email) {
        return NextResponse.json(
            { error: "Missing token or email parameters" },
            { status: 400 }
        );
    }

    try {
        // 1. Try HMAC token verification first (for links from /api/auth/generate-invite)
        const isHmacValid = verifyMagicToken(token, email);

        if (isHmacValid) {
            console.log(`[AUTH] HMAC token verified for ${email}`);
        } else {
            // 2. Fallback: verify the lead exists in Zoho
            //    This supports tokens generated by Zoho workflows (e.g. timestamp-based tokens)
            //    Security: only emails that exist as Zoho leads can proceed
            console.log(`[AUTH] HMAC verification failed, falling back to Zoho lead check for ${email}`);

            const lead = await getLeadByEmail(email);

            if (!lead) {
                console.log(`[AUTH] No Zoho lead found for ${email}, rejecting`);
                return NextResponse.json(
                    { error: "Invalid or expired magic link" },
                    { status: 401 }
                );
            }

            console.log(`[AUTH] Zoho lead verified: ${lead.id} for ${email}`);
        }

        // 3. Fetch lead details for user creation (best-effort)
        let leadFirstName: string | undefined;
        let leadLastName: string | undefined;

        try {
            const lead = await getLeadByEmail(email);
            if (lead) {
                leadFirstName = lead.First_Name || undefined;
                leadLastName = lead.Last_Name || undefined;
            }
        } catch (zohoError: any) {
            console.warn(`[AUTH] Zoho lookup failed: ${zohoError.message}`);
        }

        // 4. Manage Clerk User
        const client = await clerkClient();

        const userList = await client.users.getUserList({
            emailAddress: [email],
        });

        let user = userList.data[0];

        if (!user) {
            user = await client.users.createUser({
                emailAddress: [email],
                firstName: leadFirstName,
                lastName: leadLastName,
                skipPasswordRequirement: true,
            });
            console.log(`[AUTH] Created Clerk user for ${email}: ${user.id}`);
        }

        // 5. Generate Sign-In Token
        const signInToken = await client.signInTokens.createSignInToken({
            userId: user.id,
            expiresInSeconds: 600,
        });

        // 6. Redirect to our accept-invite page (NOT Clerk's hosted page)
        const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
        const redirectUrl = new URL("/accept-invite", appUrl);
        redirectUrl.searchParams.set("ticket", signInToken.token);
        return NextResponse.redirect(redirectUrl.toString());

    } catch (error: any) {
        console.error("Auth flow error:", error);
        return NextResponse.json(
            { error: "Authentication failed", details: error.message },
            { status: 500 }
        );
    }
}
