import { NextRequest, NextResponse } from "next/server";
import { clerkClient } from "@clerk/nextjs/server";
import { getLeadByEmail } from "@/lib/zoho";
import { verifyMagicToken } from "@/lib/magic-token";
import { query } from "@/lib/db";

export async function GET(request: NextRequest) {
    const searchParams = request.nextUrl.searchParams;
    const token = searchParams.get("token");
    const email = searchParams.get("email");

    if (!token || !email) {
        return NextResponse.json(
            { error: "Missing token or email parameters" },
            { status: 400 }
        );
    }

    try {
        // 1. Try HMAC token verification first (for links from /api/auth/generate-invite)
        const isHmacValid = verifyMagicToken(token, email);

        if (isHmacValid) {
            console.log(`[AUTH] HMAC token verified for ${email}`);
        } else {
            // 2. Fallback: verify the lead exists in Zoho
            //    This supports tokens generated by Zoho workflows (e.g. timestamp-based tokens)
            //    Security: only emails that exist as Zoho leads can proceed
            console.log(`[AUTH] HMAC verification failed, falling back to Zoho lead check for ${email}`);

            const lead = await getLeadByEmail(email);

            if (!lead) {
                console.log(`[AUTH] No Zoho lead found for ${email}, rejecting`);
                return NextResponse.json(
                    { error: "Invalid or expired magic link" },
                    { status: 401 }
                );
            }

            console.log(`[AUTH] Zoho lead verified: ${lead.id} for ${email}`);
        }

        // 3. Fetch lead details for user creation (best-effort)
        let leadFirstName: string | undefined;
        let leadLastName: string | undefined;
        let leadPhone: string | undefined;

        try {
            const lead = await getLeadByEmail(email);
            if (lead) {
                leadFirstName = lead.First_Name || undefined;
                leadLastName = lead.Last_Name || undefined;
                leadPhone = lead.Phone || lead.Mobile || undefined;
            }
        } catch (zohoError: any) {
            console.warn(`[AUTH] Zoho lookup failed: ${zohoError.message}`);
        }

        // 4. Manage Clerk User
        const client = await clerkClient();

        const userList = await client.users.getUserList({
            emailAddress: [email],
        });

        let user = userList.data[0];

        if (!user) {
            user = await client.users.createUser({
                emailAddress: [email],
                firstName: leadFirstName,
                lastName: leadLastName,
                skipPasswordRequirement: true,
            });
            console.log(`[AUTH] Created Clerk user for ${email}: ${user.id}`);
        }

        // 5. Get phone number from DB (more reliable than Zoho)
        let phone = leadPhone || "";
        try {
            const dbResult = await query(
                `SELECT id, phone FROM users WHERE clerk_id = $1 LIMIT 1`,
                [user.id]
            );
            if (dbResult.rows[0]?.phone) {
                phone = dbResult.rows[0].phone;
            }
        } catch (dbErr: any) {
            console.warn(`[AUTH] DB phone lookup failed: ${dbErr.message}`);
        }

        // 6. Get internal user ID for OTP verification flow
        let internalUserId = "";
        try {
            const dbResult = await query(
                `SELECT id FROM users WHERE clerk_id = $1 LIMIT 1`,
                [user.id]
            );
            internalUserId = dbResult.rows[0]?.id?.toString() || "";
        } catch (dbErr: any) {
            console.warn(`[AUTH] DB user lookup failed: ${dbErr.message}`);
        }

        // 7. Redirect to OTP verification page (NOT accept-invite)
        const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://www.energdive.com";
        const redirectUrl = new URL("/verify-access", appUrl);
        redirectUrl.searchParams.set("userId", internalUserId);
        redirectUrl.searchParams.set("email", email);
        if (leadFirstName) redirectUrl.searchParams.set("name", leadFirstName);

        if (phone) {
            const cleanPhone = phone.replace(/[^0-9]/g, "");
            const masked =
                "•".repeat(Math.max(0, cleanPhone.length - 4)) +
                cleanPhone.slice(-4);
            redirectUrl.searchParams.set("maskedPhone", masked);
            redirectUrl.searchParams.set("phone", cleanPhone);
        }

        console.log(`[AUTH] Redirecting ${email} to OTP verification page`);
        return NextResponse.redirect(redirectUrl.toString());

    } catch (error: any) {
        console.error("Auth flow error:", error);
        return NextResponse.json(
            { error: "Authentication failed", details: error.message },
            { status: 500 }
        );
    }
}
